version: "3.5"

services:
  db:
    container_name: tfe_db
    image: postgres:10.4
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env.prod
  api:
    hostname: api
    container_name: tfe_api
    stdin_open: true
    tty: true
    image: ${DOCKER_REGISTRY}/api:${TAG}
    build:
      context: .
      dockerfile: Dockerfile.prod
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/api/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: gunicorn tfecreative.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db
    env_file:
      - ./.env.prod
  nginx:
    container_name: tfe_nginx
    image: ${DOCKER_REGISTRY}/nginx:${TAG}
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
    volumes:
      - static_volume:/home/app/api/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
volumes:
  static_volume:
